Added hide and share page features to PDF Viewer
mrraghur/koodo-reader pull request #1
Opened 2024-02-04 06:47 UTC by har5hcodes

## Description

2024-02-05 06:55 UTC, mrraghur requested changes

2024-02-05 06:55 UTC, mrraghur commented on src/assets/styles/style.css
> -  src:  url('fonts/icomoon.eot?dhgwex#iefix') format('embedded-opentype'),
You need to preserve original formatting, unless the change is for formatting change. Revert these

2024-02-05 06:55 UTC, mrraghur commented on src/components/shareNotifier/shareNotifier.tsx
> +const ShareNotifier: React.FC = () => {
Add comments. I have no idea why we need this file/code

2024-02-05 06:55 UTC, mrraghur commented on src/pages/pdfReader/component.tsx
> +      console.error("Unable to get current page number");
When would current page number be null?

2024-02-05 06:55 UTC, mrraghur commented on src/pages/pdfReader/component.tsx
> +              hiddenPages: this.state.hiddenPages,
I wonder what happens when hiddenPages array is too long

2024-02-05 06:55 UTC, mrraghur commented on src/pages/pdfReader/component.tsx
> +        toast.success(`Page ${currentPage} is hidden`, { duration: 2000 });
replace 2000 with a constant that I can change later.

2024-02-05 06:55 UTC, mrraghur commented on src/pages/pdfReader/component.tsx
> +        toast.success("Link copied to clipboard!", { duration: 2000 });
replace 2000 here and elsewhere with a constant.

2024-02-05 06:55 UTC, mrraghur commented on src/pages/pdfReader/component.tsx
> +      console.log(iframe.contentWindow.PDFViewerApplication.page);
Why do we need this console.log statement? you can make it console.debug?

2024-02-05 06:55 UTC, mrraghur commented on src/pages/pdfReader/component.tsx
> +      .getItem("hiddenPages")
Add comments plz. Here and elsewhere

2024-02-07 04:17 UTC, har5hcodes commented on src/assets/styles/style.css
> -  src:  url('fonts/icomoon.eot?dhgwex#iefix') format('embedded-opentype'),
It occurred because I use a formatting extension in VS Code that automatically formats the code whenever I save a file

2024-02-07 04:29 UTC, har5hcodes commented on src/components/shareNotifier/shareNotifier.tsx
> +const ShareNotifier: React.FC = () => {
I initially planned to create separate components for each feature I was working on. I now, integrated the event listener directly into the Viewer component, removing the need for separate ones like ShareNotifier.

2024-03-12 03:05 UTC, mrraghur approved these changes

2024-03-12 03:05 UTC, mrraghur commented on src/components/bookCardItem/component.tsx
> +      new Date().getTime() >= parseInt(tokenExpiresByString, 10)
You need to stop hardcoding numbers like this. 
They are called magic numbers. Readup about them.

2024-03-12 03:05 UTC, mrraghur commented on src/components/importLocal/component.tsx
> +      gdriveFileId: "",
hardcoded value. You should create constant called EMPTY_STRING and use it here.

2024-03-12 03:05 UTC, mrraghur commented on src/components/importLocal/component.tsx
> +      cbt: "application/x-cbr",
x-cbr or x-cbt?

2024-03-12 03:05 UTC, mrraghur commented on src/components/importLocal/component.tsx
> +      let fileId = "";
empty_string

2024-03-12 03:06 UTC, merged